///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTestSourcecodeCheckin
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTestSourcecodeCheckinRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("541eb477-ad73-4536-beb7-04089e58f974")]
    public partial class MyTestSourcecodeCheckinRepository : RepoGenBaseFolder
    {
        static MyTestSourcecodeCheckinRepository instance = new MyTestSourcecodeCheckinRepository();

        /// <summary>
        /// Gets the singleton class instance representing the MyTestSourcecodeCheckinRepository element repository.
        /// </summary>
        [RepositoryFolder("541eb477-ad73-4536-beb7-04089e58f974")]
        public static MyTestSourcecodeCheckinRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTestSourcecodeCheckinRepository() 
            : base("MyTestSourcecodeCheckinRepository", "/", null, 0, false, "541eb477-ad73-4536-beb7-04089e58f974", ".\\RepositoryImages\\MyTestSourcecodeCheckinRepository541eb477.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("541eb477-ad73-4536-beb7-04089e58f974")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTestSourcecodeCheckinRepositoryFolders
    {
    }
#pragma warning restore 0436
}
